name: Books Service build and publish Docker image
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "${{toJSON(github.event.pull_request.merged)}}"
