name: Books Service build and publish Docker image
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  push_to_registry:
    # If pull request was merged and was from service-books
    if: (github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'feature/service-books')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "${{toJSON(github.event.pull_request.merged)}}"
          echo "${{toJSON(github.event.pull_request.head.ref)}}"
          echo "${{toJSON((github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'test'))}}"
